### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by emilx-cell** [Aleph-Alpha/trigrams#1]
Hi,
Are you planning to release the code? the repo is empty.
Thanks,
EL.

**Comment by bashFish** [comment]
cheers, we finish some house keeping and will release the code this month. thanks for asking

**Comment by DustinEwan** [comment]
Just wondering if there's any updates on this. I've attempted to implement this myself, but some things aren't obvious from the paper itself and was hoping a codebase would clarify. 

Thanks so much! Super interesting!

**Comment by bashFish** [comment]
cheers, we just published the codebase.
a 7B trained on 1 epoch of fineweb-edu is almost done, will publish that along with some evals soonish

**Comment by bashFish** [comment]
@DustinEwan for anything unclear don't hesitate to contact us :)

greets
bjoern

**Comment by DustinEwan** [comment]
@bashFish thanks so much for releasing the code!  I've been going through it and, while I appreciate the thoroughness, perhaps a very minimal example of how to use the tokenizer and how to ingest the tokens would be a good exercise.

Like a single file that just walks through setting up a simple model (like GPT-2, or maybe even simpler than that), tokenizing some sample test data, and then passing batch sample input to the model.

Having a full trainer, dataset, etc., built out is nice for eliminating dependencies on third parties like huggingface or the sort, but it unfortunately blurs the boundary between what is unique to T-Free and what is structural code for setting up the training and inference environment.

Again, thank you very much for providing the code!  It's very interesting and I'm eager to give it a go in my own projects!  I just wanted to give you a heads up that there's a lot to dig through for a newcomer to the codebase.
